### ISSUE TITLE
Does Not Build

### ISSUE THREAD

**Issue by steviebeenz** [GhastD/JI-Anticheat#1]
When you run the mvn command / mvn clean install / package it gives you an error parsing the pom.xml.

Ghastly Anticheat doesn't even compile.

**Comment by steviebeenz** [comment]
@GhastD is this a troll to try and reduce leaks?

**Comment by GhastD** [comment]
You are aware that:
1. This is only the core
2. It’s not done, barely even completed 
3. It’s missing the checks module, intentionally removed because no peeking

**Comment by steviebeenz** [comment]
@GhastD so is this to allow people to develop their own checks?

**Comment by GhastD** [comment]
Not even it’s just for the sake of having it open sourced
